# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.singihl.com:
    container_name: orderer.singihl.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=MOEMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/singihl.com/orderers/orderer.singihl.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/singihl.com/orderers/orderer.singihl.com/tls/:/var/hyperledger/orderer/tls
    - orderer.singihl.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.ntu.singihl.com:
    container_name: peer0.ntu.singihl.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.ntu.singihl.com
      - CORE_PEER_ADDRESS=peer0.ntu.singihl.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.ntu.singihl.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ntu.singihl.com:7051
      - CORE_PEER_LOCALMSPID=NTUMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/ntu.singihl.com/peers/peer0.ntu.singihl.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/ntu.singihl.com/peers/peer0.ntu.singihl.com/tls:/etc/hyperledger/fabric/tls
        - peer0.ntu.singihl.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.ntu.singihl.com:
    container_name: peer1.ntu.singihl.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.ntu.singihl.com
      - CORE_PEER_ADDRESS=peer1.ntu.singihl.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.ntu.singihl.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ntu.singihl.com:7051
      - CORE_PEER_LOCALMSPID=NTUMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/ntu.singihl.com/peers/peer1.ntu.singihl.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/ntu.singihl.com/peers/peer1.ntu.singihl.com/tls:/etc/hyperledger/fabric/tls
        - peer1.ntu.singihl.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer2.ntu.singihl.com:
    container_name: peer2.ntu.singihl.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.ntu.singihl.com
      - CORE_PEER_ADDRESS=peer2.ntu.singihl.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.ntu.singihl.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ntu.singihl.com:7051
      - CORE_PEER_LOCALMSPID=NTUMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/ntu.singihl.com/peers/peer2.ntu.singihl.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/ntu.singihl.com/peers/peer2.ntu.singihl.com/tls:/etc/hyperledger/fabric/tls
        - peer2.ntu.singihl.com:/var/hyperledger/production

    ports:
      - 9051:7051
      - 9053:7053    

  peer0.nus.singihl.com:
    container_name: peer0.nus.singihl.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.nus.singihl.com
      - CORE_PEER_ADDRESS=peer0.nus.singihl.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.nus.singihl.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.nus.singihl.com:7051
      - CORE_PEER_LOCALMSPID=NUSMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/nus.singihl.com/peers/peer0.nus.singihl.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/nus.singihl.com/peers/peer0.nus.singihl.com/tls:/etc/hyperledger/fabric/tls
        - peer0.nus.singihl.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053

  peer1.nus.singihl.com:
    container_name: peer1.nus.singihl.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.nus.singihl.com
      - CORE_PEER_ADDRESS=peer1.nus.singihl.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.nus.singihl.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.nus.singihl.com:7051
      - CORE_PEER_LOCALMSPID=NUSMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/nus.singihl.com/peers/peer1.nus.singihl.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/nus.singihl.com/peers/peer1.nus.singihl.com/tls:/etc/hyperledger/fabric/tls
        - peer1.nus.singihl.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053
