# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.singihl.com:
  peer0.ntu.singihl.com:
  peer1.ntu.singihl.com:
  peer2.ntu.singihl.com:
  # peer3.ntu.singihl.com:
  # peer4.ntu.singihl.com:
  peer0.nus.singihl.com:
  peer1.nus.singihl.com:
  # peer2.nus.singihl.com:  

networks:
  ihl:

services:

  orderer.singihl.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.singihl.com
    container_name: orderer.singihl.com
    networks:
      - ihl

  peer0.ntu.singihl.com:
    container_name: peer0.ntu.singihl.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.ntu.singihl.com
    networks:
      - ihl

  peer1.ntu.singihl.com:
    container_name: peer1.ntu.singihl.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.ntu.singihl.com
    networks:
      - ihl

  peer2.ntu.singihl.com:
    container_name: peer2.ntu.singihl.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer2.ntu.singihl.com
    networks:
      - ihl

  # peer3.ntu.singihl.com:
  #   container_name: peer3.ntu.singihl.com
  #   extends:
  #     file:  base/docker-compose-base.yaml
  #     service: peer3.ntu.singihl.com
  #   networks:
  #     - ihl

  # peer4.ntu.singihl.com:
  #   container_name: peer4.ntu.singihl.com
  #   extends:
  #     file:  base/docker-compose-base.yaml
  #     service: peer4.ntu.singihl.com
  #   networks:
  #     - ihl

  peer0.nus.singihl.com:
    container_name: peer0.nus.singihl.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.nus.singihl.com
    networks:
      - ihl

  peer1.nus.singihl.com:
    container_name: peer1.nus.singihl.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.nus.singihl.com
    networks:
      - ihl

  # peer2.nus.singihl.com:
  #   container_name: peer2.nus.singihl.com
  #   extends:
  #     file:  base/docker-compose-base.yaml
  #     service: peer2.nus.singihl.com
  #   networks:
  #     - ihl

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.ntu.singihl.com:7051
      - CORE_PEER_LOCALMSPID=NTUMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ntu.singihl.com/peers/peer0.ntu.singihl.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ntu.singihl.com/peers/peer0.ntu.singihl.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ntu.singihl.com/peers/peer0.ntu.singihl.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ntu.singihl.com/users/Admin@peer0.ntu.singihl.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.singihl.com
      - peer0.ntu.singihl.com
      - peer1.ntu.singihl.com
      - peer2.ntu.singihl.com
      #- peer3.ntu.singihl.com
      #- peer4.ntu.singihl.com
      - peer0.nus.singihl.com
      - peer1.nus.singihl.com
      #- peer2.nus.singihl.com  

    networks:
      - ihl
